// FactoryX
//
// Copyright ©2002- 2018 by FactoryX, Netherlands/Australia
//
// Project: Media Foundation - MFPack - Samples
// Project location: http://sourceforge.net/projects/MFPack
// Module: subtitleConv-lang-eng.inc
// Kind: Pascal Unit
// Release date: 24-01-2003
// Language: ENU
//
// Version: 1.2.1
// Description: SRT and SMIL/SAMI parser/converter.
//
//
// Intiator(s): Tony (maXcomX)
//
//
// ----------------------------------------------------------------------------
// CHANGE LOG
// Date       Person              Reason
// ---------- ------------------- ---------------------------------------------
// ----------------------------------------------------------------------------
//
// Remarks:
//
// Related objects: -
// Related projects: MfPack
// Known Issues: -
// Compiler version: 17 up to 21
// Todo: -
// SDK version: 10.0.16299.15
// =============================================================================
// Source: -
//==============================================================================
//
// LICENSE
//
// The contents of this file are subject to the Mozilla Public License
// Version 1.1 (the "License"); you may not use this file except in
// compliance with the License. You may obtain a copy of the License at
// http://www.mozilla.org/MPL/MPL-1.1.html
//
// Software distributed under the License is distributed on an "AS IS"
// basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
// License for the specific language governing rights and limitations
// under the License.
//
// Groupname: FactoryX
// The Initial Developers of the Original Code are: Tony Kalf (maXcomX)
//                                                  Peter Larson (ozships)
//
// Contributor(s): Tony Kalf (maXcomX),
//                 Peter Larson (ozships).
//
// Users may distribute this source code provided that this header is included
// in full at the top of the file.
//
//==============================================================================

//messages
MSG16 = 'Error while reading subtitle file.';
MSG17 = 'Wrong subtitle SMIL/SAMI file.';
MSG19 = 'Error while converting SRT file: Wrong format!';
MSG20 = 'Conversion done.';
MSG21 = 'Conversion succesfully done.';
MSG21A = 'Converted file saved as:';
ERR09 = 'No SMI text available.';
ERR10 = 'No SMIL/SAMI subtitle file.';
WRNXX = 'Error';